language:  python
python:
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
env:
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11.1
services: 
  - docker
# command to install dependencies
# install: "pip install -r requirements.txt"
#before_install:
#  - docker build -t 
#  - docker run -d -p 
#  - docker ps -a
#  - docker run 
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django-cors-headers
# command to run tests
script: 
  - cd jpsp
  - python manage.py runserver
